### PR TITLE
Add ability to follow a user(s) tweets using setFollow()

### PR DESCRIPTION
**Pull request by brentkozjak**
This allows you to follow a one or more users tweets using a whenTweets() method.  Under the hood, it's using setFollow() instead of setTrack().

### CODE REVIEW

**Comment by freekmurze** [comment]
To make it clear: `$listenFor` should be a string or array of twitter handles? If so, rename that variable to `$twitterHandles`. Could you also update the readme with a good description of the added functionality?

**Comment by brentkozjak** [comment]
`$listenFor` must be a string or array of Twitter User ID's as per https://dev.twitter.com/streaming/overview/request-parameters#follow 

Perhaps `$twitterUserIds` would be more appropriate?

**Comment by freekmurze** [comment]
`$twitterUserIds` sounds good to me 👍

**Comment by bradbernard** [comment]
+1 need to filter on user IDs. When will this be merged?

**Comment by freekmurze** [comment]
Probably in the next couple of days

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
