### PR TITLE
update ci and code quality tools

### PR DESCRIPTION
**Pull request by felixdorn**
This PR updates the build tooling to the latest Spatie standards. I've made no opinionated changes, just copy/pasted configurations from the skeleton package package.

As this package is not working in it's current state, I'm also working on fixes to make it work, so it'd be nice to have this PR merged so my fork can already use GitHub Actions and see early if the CI fails on old versions of PHP

### CODE REVIEW

**Comment by felixdorn** [comment]
To elaborate a bit more,
* I've removed StyleCI and TravisCI in favor of GitHub Actions.
* Made Psalm happy
* I've updated issue templates, security.md, etc...

**Comment by freekmurze** [comment]
fyi I wouldn't mind at all if support for PHP 7 would be dropped.

**Comment by felixdorn** [comment]
This PR can now be merged, if you're satisfied with the changes, of course.

**Comment by felixdorn** [comment]
I believe StyleCI does not suppport PHP8, that's why it fails.

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
@felixdorn Seems like the cs fixer is failing. Could you take a look at that?

**Comment by felixdorn** [comment]
@freekmurze Done, see #29

**Pull request merged**
