### PR TITLE
Make this package work again

### PR DESCRIPTION
**Pull request by felixdorn**
Hey!

This replaces phirehose with a new package to make everything work.

There are some breaking changes :

Constructor of PublicStream and UserStream has changed to match new auth requirements from Twitter.

Requires PHP8.

### CODE REVIEW

**Comment by felixdorn** [comment]
Hey @freekmurze, this is ready.

**Comment by freekmurze** [comment]
I'll tag this as a new major version. Have you tested this against the live Twitter API and are sure that everything works correctly?

**Comment by felixdorn** [comment]
Yes! I did and it works.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
